name: nemspy
channels:
  - conda-forge
dependencies:
  - bs4
  - fiona
  - geopandas
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - psutil
  - pyproj
  - requests
  - scipy
  - seaborn
  - shapely
  - pip:
      - adcircpy
      - coverage
      - coverage-badge
      - eventlet
      - flake8
      - haversine
      - nose
      - ordered-set
      - paramiko
      - rednose
      - requests_futures
      - utm
      - wget
